### PR TITLE
v1.7.2-beta.11 - final

### PR DESCRIPTION
**Pull request by DMBlakeley**
Believe that I have pull request correct this time ...

Update provides recovery from `refreshDevices()` or `loginServices()` errors when polling Alarm.com for device changes by refreshing account login on next timer loop.
* Renamed `login()` to `loginSession()` to avoid confusion with `login` in `node-alarm-dot-com node` module.
* Reformat `loginSession()` as async function with error reporting.
* Syntactical TypeScript updates flagged by VS Code.
* Updated `package.json` and `package-lock.json` packages to latest versions.
* Using `node-fetch@v3.00-beta.9` and `node-alarm-dot-com@beta.6`.

Also posted `DMBlakeley/node-alarm-dot-com-beta.7` which update to explicitly declare `async` functions.  PR compatible with either `beta.6` or `beta-7`.

Change should address issues #62, #74, #75. Does not prevent errors as they seem to be inherent with Alarm.com communication but recovers more smoothly.

### CODE REVIEW

**Comment by chase9** [comment]
Sorry this took so long. I started several weeks ago but was overwhelmed as your repos did not share a history. It's been merged.

**Comment by DMBlakeley** [comment]
I was going to close this PR in favor of the changes that I have made in the `homebridge-node-alarm-dot-com-2` branch which uses of `node-alarm-dot-com-2@1.11.0-beta.7`.

There are a number of other updates in this package:

- update workflows to use node-version: [12.x, 14.x, 16.x] and drops 10.x
- fixes node-fetch at 3.0.0-beta.9 as beta.10 use ESM format which is not compatible with this file

Probably best if I submit a new PR with these changes.

**Comment by chase9** [comment]
I believe the only changed not merged as of this point are moving node-fetch to 3 due to the breaking changed you mentioned. Is there something you'd like me to prioritize?

**Comment by DMBlakeley** [comment]
Let me compare what you now have posted with beta.11/beta.8 and see if there are any additional updates.

**Comment by DMBlakeley** [comment]
Looks like you have pulled all of the index.ts changes for both packages from my com-2 branch into beta.11 and it is running fine on my RPi test unit as well as my Mac main unit.

As I will be losing access to Alarm.com when we move at the end of the month I will change my branch from `public` to `private` so that they are no longer visible and will `unpublish` the `com-2` versions from npm so there is no confusion.

**Pull request closed without merging**
